# Generated by tools/pixellab_export.py - do not edit by hand.
# PixelLab barrel (2026-10-03): frame 0 whole, 0-8 burst apart, 8 = wreck.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/barrel_pl/barrel_0000.png",
	"res://art/barrel_pl/barrel_0001.png",
	"res://art/barrel_pl/barrel_0002.png",
	"res://art/barrel_pl/barrel_0003.png",
	"res://art/barrel_pl/barrel_0004.png",
	"res://art/barrel_pl/barrel_0005.png",
	"res://art/barrel_pl/barrel_0006.png",
	"res://art/barrel_pl/barrel_0007.png",
	"res://art/barrel_pl/barrel_0008.png",
]
