# Generated by tools/pixellab_export.py - do not edit by hand.
# PixelLab pressure cauldron (create_image_pixflux, 2026-10-04), stray flame on the right erased. One still frame; bubbling/shake is done in code for now.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/cauldron_pl/cauldron_0000.png",
]
