# Generated by tools/pixelize_sprites.py - do not edit.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/rusher_walk_px/rusher_walk_a00_0001.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0002.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0003.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0004.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0005.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0006.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0007.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0008.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0009.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0010.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0011.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0012.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0013.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0014.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0015.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0016.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0017.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0018.png",
	"res://art/rusher_walk_px/rusher_walk_a00_0019.png",
]
