# Generated by tools/pixelize_sprites.py - do not edit.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/farby_v01_px/farby_v01_a00_0181.png",
]
