# Generated by tools/pixellab_export.py - do not edit by hand.
# Ceramic pot variant a (PixelLab pixflux 2026-10-09), whole frame only, preview
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/pot_a_pl/pot_0000.png",
]
