# Generated by tools/pixellab_export.py - do not edit by hand.
# Gunman collapse (PixelLab custom v3, 2026-10-09). Mirrored: faces west, collapses to the knees and topples FORWARD (toward -x); corpses.gd flips it with the enemy.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/gunman_pl_death/death_0000.png",
	"res://art/gunman_pl_death/death_0001.png",
	"res://art/gunman_pl_death/death_0002.png",
	"res://art/gunman_pl_death/death_0003.png",
	"res://art/gunman_pl_death/death_0004.png",
	"res://art/gunman_pl_death/death_0005.png",
	"res://art/gunman_pl_death/death_0006.png",
	"res://art/gunman_pl_death/death_0007.png",
	"res://art/gunman_pl_death/death_0008.png",
	"res://art/gunman_pl_death/death_0009.png",
	"res://art/gunman_pl_death/death_0010.png",
	"res://art/gunman_pl_death/death_0011.png",
	"res://art/gunman_pl_death/death_0012.png",
]
