# Generated by tools/pixellab_export.py - do not edit by hand.
# PixelLab gunman v2: the east rotation as a one-frame idle (no idle clip generated yet - saves a credit).
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/gunman_pl_idle/idle_0000.png",
]
