# Generated by tools/pixelize_sprites.py - do not edit.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/rusher_scan_px/rusher_scan_a00_0001.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0009.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0017.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0025.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0033.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0041.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0049.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0057.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0065.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0073.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0081.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0089.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0097.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0105.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0113.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0121.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0129.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0137.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0145.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0153.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0161.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0169.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0177.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0185.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0193.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0201.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0209.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0217.png",
	"res://art/rusher_scan_px/rusher_scan_a00_0225.png",
]
