# Generated by tools/pixellab_export.py - do not edit by hand.
# PixelLab gunman v2, v3 custom 'raise, aim, fire, recoil, lower' (108 px canvas, reference
# at 16,16 -> -2,12 on the shared 104). Muzzle flash on frame 5: the shot leaves
# then (THROWER_SHOT_DELAY), not when the clip starts.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/gunman_pl_fire/fire_0000.png",
	"res://art/gunman_pl_fire/fire_0001.png",
	"res://art/gunman_pl_fire/fire_0002.png",
	"res://art/gunman_pl_fire/fire_0003.png",
	"res://art/gunman_pl_fire/fire_0004.png",
	"res://art/gunman_pl_fire/fire_0005.png",
	"res://art/gunman_pl_fire/fire_0006.png",
	"res://art/gunman_pl_fire/fire_0007.png",
	"res://art/gunman_pl_fire/fire_0008.png",
]
