# Generated by tools/pixelize_sprites.py - do not edit.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/gunman_uhly_px/gunman_uhly_a00_0040.png",
	"res://art/gunman_uhly_px/gunman_uhly_a01_0040.png",
	"res://art/gunman_uhly_px/gunman_uhly_a02_0040.png",
	"res://art/gunman_uhly_px/gunman_uhly_a03_0040.png",
	"res://art/gunman_uhly_px/gunman_uhly_a04_0040.png",
	"res://art/gunman_uhly_px/gunman_uhly_a05_0040.png",
	"res://art/gunman_uhly_px/gunman_uhly_a06_0040.png",
]
