# Generated by tools/pixellab_export.py - do not edit by hand.
# PixelLab gunman v2 (spiked helmet, blue coat), template walking-8-frames, east mirrored to west.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/gunman_pl_walk/walk_0000.png",
	"res://art/gunman_pl_walk/walk_0001.png",
	"res://art/gunman_pl_walk/walk_0002.png",
	"res://art/gunman_pl_walk/walk_0003.png",
	"res://art/gunman_pl_walk/walk_0004.png",
	"res://art/gunman_pl_walk/walk_0005.png",
	"res://art/gunman_pl_walk/walk_0006.png",
	"res://art/gunman_pl_walk/walk_0007.png",
]
