# Generated by tools/pixellab_export.py - do not edit by hand.
# Ceramic pot (PixelLab pixflux base 2026-10-09, lightened; animate_image 8 frames): frame 0 whole, 1-8 shatters into a pile, 8 = wreck. Stray white sparks removed.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/pot_pl/pot_0000.png",
	"res://art/pot_pl/pot_0001.png",
	"res://art/pot_pl/pot_0002.png",
	"res://art/pot_pl/pot_0003.png",
	"res://art/pot_pl/pot_0004.png",
	"res://art/pot_pl/pot_0005.png",
	"res://art/pot_pl/pot_0006.png",
	"res://art/pot_pl/pot_0007.png",
	"res://art/pot_pl/pot_0008.png",
]
