# Generated by tools/pixellab_export.py - do not edit by hand.
# Brute idle: the east rotation as one frame.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/brute_pl_idle/idle_0000.png",
]
