# Generated by tools/pixellab_export.py - do not edit by hand.
# PixelLab hero standing with the axe in hand, breathing loop (2026-10-03).
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/hero_pl_axe_idle/idle_0000.png",
	"res://art/hero_pl_axe_idle/idle_0001.png",
	"res://art/hero_pl_axe_idle/idle_0002.png",
	"res://art/hero_pl_axe_idle/idle_0003.png",
	"res://art/hero_pl_axe_idle/idle_0004.png",
	"res://art/hero_pl_axe_idle/idle_0005.png",
	"res://art/hero_pl_axe_idle/idle_0006.png",
]
