# Generated by tools/pixellab_export.py - do not edit by hand.
# Rusher fall (PixelLab falling-back-death, 2026-10-08). Mirrored: falls toward +x (east); corpses.gd flips it. Frames 5 and 6 shifted down so the lying body touches the ground row.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/rusher_pl_death/death_0000.png",
	"res://art/rusher_pl_death/death_0001.png",
	"res://art/rusher_pl_death/death_0002.png",
	"res://art/rusher_pl_death/death_0003.png",
	"res://art/rusher_pl_death/death_0004.png",
	"res://art/rusher_pl_death/death_0005.png",
	"res://art/rusher_pl_death/death_0006.png",
]
