# Generated by tools/pixellab_export.py - do not edit by hand.
# PixelLab hero, overhand axe throw (2026-10-03). Frames 1,2,4,5,6 wind-up,
# 7 = arm forward, axe gone (stray axe pixels behind the back erased).
# The axe leaves the hand at Tuning.AXE_RELEASE_FRAME (index in THIS list).
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/hero_pl_axe_throw/throw_0001.png",
	"res://art/hero_pl_axe_throw/throw_0002.png",
	"res://art/hero_pl_axe_throw/throw_0004.png",
	"res://art/hero_pl_axe_throw/throw_0005.png",
	"res://art/hero_pl_axe_throw/throw_0006.png",
	"res://art/hero_pl_axe_throw/throw_0007.png",
	"res://art/hero_pl_axe_throw/throw_0007.png",
]
