# Generated by tools/pixellab_export.py - do not edit by hand.
# Brute grab: v3 custom, lunge then a held squeeze (last two frames repeat).
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/brute_pl_grab/grab_0000.png",
	"res://art/brute_pl_grab/grab_0001.png",
	"res://art/brute_pl_grab/grab_0002.png",
	"res://art/brute_pl_grab/grab_0003.png",
	"res://art/brute_pl_grab/grab_0004.png",
	"res://art/brute_pl_grab/grab_0005.png",
	"res://art/brute_pl_grab/grab_0006.png",
	"res://art/brute_pl_grab/grab_0005.png",
	"res://art/brute_pl_grab/grab_0006.png",
	"res://art/brute_pl_grab/grab_0005.png",
	"res://art/brute_pl_grab/grab_0006.png",
	"res://art/brute_pl_grab/grab_0005.png",
	"res://art/brute_pl_grab/grab_0006.png",
]
