"""Slavs - re-pixelate a rendered sprite folder at a different pixel size.

Why this exists: how coarse a character's pixels are, relative to the ground it
walks on, is a question about a picture, and METHOD rule 1 says those are
decided by looking at the picture rather than by describing it. Re-rendering
every clip in Blender to try one coarseness is a night's work; this does it in
seconds from the frames that already exist, so the two can be put side by side
on the phone and one of them picked.

It is NOT a replacement for rendering. A frame produced here has been through
the pixel pass twice, so it is very slightly softer than the same frame rendered
straight from Blender at that height. Good enough to choose with; re-render the
winner properly (PRIKAZY.md) before it ships.

    python tools/coarsen_sprites.py --in slavs/art/run_px --out slavs/art/run_px_b --height 108

Writes the PNGs and the frames.gd manifest. It does NOT write .import files -
`godot --headless --import` (already part of tools/deploy_android.ps1) makes
those, and letting Godot own them avoids inventing uids that collide.
"""

import argparse
import pathlib
import sys

import numpy as np
from PIL import Image, ImageFilter

MANIFEST_HEADER = """# Generated by tools/coarsen_sprites.py - do not edit.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
"""


def pixelate(img: Image.Image, target_h: int, colours: int, outline: bool,
             darken: float = 0.0) -> Image.Image:
    """Shrink to target_h, harden the alpha, quantise, and ring it in dark.

    The whole canvas is scaled, not the character inside it, so the empty rows
    the renderer leaves below the feet shrink by the same factor. Anything
    measured from those margins - foot placement, muzzle height, the hurtbox -
    therefore stays correct without touching the game.
    """
    w = max(1, round(img.width * target_h / img.height))
    small = img.resize((w, target_h), Image.BOX)

    alpha = np.asarray(small.getchannel("A"))
    mask = Image.fromarray(np.where(alpha > 110, 255, 0).astype(np.uint8), "L")

    rgb = small.convert("RGB").quantize(
        colors=colours, method=Image.MEDIANCUT).convert("RGB")
    out = Image.new("RGBA", small.size, (0, 0, 0, 0))
    out.paste(rgb, (0, 0), mask)

    if outline:
        out = add_outline(out, darken)
    return out


def add_outline(im: Image.Image, darken: float) -> Image.Image:
    """Same ring as pixelize_sprites.outline(), kept in step with it.

    darken = 0 gives the flat near-black edge; above 0 the ring takes the
    colour of the body it touches, multiplied by that factor.
    """
    arr = np.asarray(im).copy()
    solid = arr[..., 3] > 0
    padded = np.pad(solid, 1)
    ring = (padded[:-2, 1:-1] | padded[2:, 1:-1] |
            padded[1:-1, :-2] | padded[1:-1, 2:]) & ~solid
    if darken <= 0.0:
        arr[ring] = (26, 20, 18, 255)
        return Image.fromarray(arr, "RGBA")
    rgb = arr[..., :3].astype(np.float32)
    total = np.zeros_like(rgb)
    count = np.zeros(solid.shape, np.float32)
    for dy, dx in ((-1, 0), (1, 0), (0, -1), (0, 1)):
        total += np.roll(np.roll(rgb, dy, 0), dx, 1) * \
                 np.roll(np.roll(solid, dy, 0), dx, 1)[..., None]
        count += np.roll(np.roll(solid, dy, 0), dx, 1)
    edge = np.clip(total / np.maximum(count, 1.0)[..., None] * darken,
                   0, 255).astype(np.uint8)
    arr[..., :3][ring] = edge[ring]
    arr[..., 3][ring] = 255
    arr[ring & (count == 0)] = (26, 20, 18, 255)
    return Image.fromarray(arr, "RGBA")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="src", required=True)
    ap.add_argument("--out", dest="dst", required=True)
    ap.add_argument("--height", type=int, required=True,
                    help="sprite height in pixels after coarsening")
    ap.add_argument("--colours", type=int, default=17)
    ap.add_argument("--no-outline", action="store_true")
    ap.add_argument("--outline-darken", type=float, default=0.0)
    args = ap.parse_args()

    src = pathlib.Path(args.src)
    dst = pathlib.Path(args.dst)
    frames = sorted(p for p in src.glob("*.png"))
    if not frames:
        print(f"Ziadne PNG v {src}", file=sys.stderr)
        return 1

    dst.mkdir(parents=True, exist_ok=True)
    written = []
    for f in frames:
        img = Image.open(f).convert("RGBA")
        pixelate(img, args.height, args.colours, not args.no_outline,
                 args.outline_darken).save(dst / f.name)
        written.append(f.name)

    # res:// path, not a filesystem path - the manifest is read by the game.
    res_dir = "res://" + str(dst).replace("\\", "/").split("slavs/", 1)[-1]
    lines = [MANIFEST_HEADER]
    lines += [f'\t"{res_dir}/{n}",\n' for n in written]
    lines.append("]\n")
    (dst / "frames.gd").write_text("".join(lines), encoding="utf-8")

    first = Image.open(dst / written[0])
    print(f"{src.name:<22} -> {dst.name:<24} {len(written):>3} snimok, {first.width}x{first.height}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
