"""Turn PixelLab frames into a Slavs art folder (2026-10-03).

Downloads (or reads) the frames of one PixelLab clip, places each on the
shared square canvas at a fixed offset so the feet sit on the same row as
every other clip of that character, applies hard alpha, optionally erases
stray pixels, writes NNNN-numbered PNGs and the frames.gd manifest the game
reads (Godot does not ship raw PNGs, so the folder cannot be listed at
runtime - the manifest can).

Example (the hero's axe throw):
    python tools/pixellab_export.py --url-base <.../animations/<id>/east> \
        --count 8 --out slavs/art/hero_pl_axe_throw --name throw \
        --offset 18 4 --order 1,2,4,5,6,7,7 \
        --erase 7:0,33,21,47 --note "Throw: release on the last frame."

--offset is where the clip's own canvas goes on the shared canvas. For the
hero the 64 px rotation sits at (20, 16) on 96 px; a v3 clip adds its own
padding, measured from its reference frame 0.
"""
import argparse
import io
import os
import urllib.request

from PIL import Image


def load(src: str) -> Image.Image:
    if src.startswith("http"):
        # A bare urllib User-Agent gets 403 from the file host.
        req = urllib.request.Request(src, headers={"User-Agent": "curl/8"})
        with urllib.request.urlopen(req, timeout=60) as r:
            return Image.open(io.BytesIO(r.read())).convert("RGBA")
    return Image.open(src).convert("RGBA")


def hard_alpha(im: Image.Image) -> Image.Image:
    px = im.load()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            px[x, y] = (r, g, b, 255) if a >= 128 else (0, 0, 0, 0)
    return im


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--url-base", help="frames are <url-base>/<i>.png")
    ap.add_argument("--files", nargs="*", help="explicit frame files/URLs")
    ap.add_argument("--count", type=int, default=0)
    ap.add_argument("--out", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--canvas", type=int, default=96)
    ap.add_argument("--offset", type=int, nargs=2, default=(0, 0))
    ap.add_argument("--order", default="", help="play order with holds, e.g. 0,1,2,2,3")
    ap.add_argument("--erase", action="append", default=[],
                    help="frame:x0,y0,x1,y1 in SOURCE pixels, inclusive")
    ap.add_argument("--note", default="")
    ap.add_argument("--shift", action="append", default=[],
                    help="frame:dx,dy extra offset of ONE frame (e.g. lets a lying body touch the ground)")
    ap.add_argument("--mirror", action="store_true",
                    help="flip horizontally AFTER placing on the canvas: "
                         "enemies are generated facing east, enemy.gd wants west")
    a = ap.parse_args()

    srcs = a.files or [f"{a.url_base}/{i}.png" for i in range(a.count)]
    erase = {}
    for e in a.erase:
        k, box = e.split(":")
        erase.setdefault(int(k), []).append(tuple(int(v) for v in box.split(",")))

    shifts = {}
    for s in a.shift:
        k, d = s.split(":")
        shifts[int(k)] = tuple(int(v) for v in d.split(","))

    os.makedirs(a.out, exist_ok=True)
    res = "res://" + a.out.replace("\\", "/").split("slavs/", 1)[1]
    names = []
    for i, src in enumerate(srcs):
        im = load(src)
        px = im.load()
        for x0, y0, x1, y1 in erase.get(i, []):
            for y in range(y0, y1 + 1):
                for x in range(x0, x1 + 1):
                    px[x, y] = (0, 0, 0, 0)
        canvas = Image.new("RGBA", (a.canvas, a.canvas), (0, 0, 0, 0))
        # paste, not alpha_composite: a v3 clip's own canvas can be bigger
        # than the shared one, so its offset may be negative.
        sdx, sdy = shifts.get(i, (0, 0))
        canvas.paste(im, (a.offset[0] + sdx, a.offset[1] + sdy), im)
        if a.mirror:
            canvas = canvas.transpose(Image.FLIP_LEFT_RIGHT)
        name = f"{a.name}_{i:04d}.png"
        hard_alpha(canvas).save(os.path.join(a.out, name))
        names.append(name)

    order = [int(v) for v in a.order.split(",")] if a.order else list(range(len(names)))
    lines = [
        "# Generated by tools/pixellab_export.py - do not edit by hand.",
    ]
    if a.note:
        lines += ["# " + l for l in a.note.split("\n")]
    lines += [
        "#",
        "# Godot does not ship the original .png files in an exported game, so",
        "# the folder cannot be listed at runtime. This list can.",
        "extends RefCounted",
        "",
        "const FRAMES: Array[String] = [",
    ]
    lines += [f'\t"{res}/{names[i]}",' for i in order]
    lines += ["]", ""]
    with open(os.path.join(a.out, "frames.gd"), "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(a.out, len(names), "png,", len(order), "in order")


if __name__ == "__main__":
    main()
