# Generated by tools/pixelize_sprites.py - do not edit.
#
# Godot does not ship the original .png files in an exported game, so
# the folder cannot be listed at runtime. This list can.
extends RefCounted

const FRAMES: Array[String] = [
	"res://art/rusher_360_px/rusher_360_a00_0049.png",
	"res://art/rusher_360_px/rusher_360_a01_0049.png",
	"res://art/rusher_360_px/rusher_360_a02_0049.png",
	"res://art/rusher_360_px/rusher_360_a03_0049.png",
	"res://art/rusher_360_px/rusher_360_a04_0049.png",
	"res://art/rusher_360_px/rusher_360_a05_0049.png",
	"res://art/rusher_360_px/rusher_360_a06_0049.png",
	"res://art/rusher_360_px/rusher_360_a07_0049.png",
	"res://art/rusher_360_px/rusher_360_a08_0049.png",
	"res://art/rusher_360_px/rusher_360_a09_0049.png",
	"res://art/rusher_360_px/rusher_360_a10_0049.png",
	"res://art/rusher_360_px/rusher_360_a11_0049.png",
	"res://art/rusher_360_px/rusher_360_a12_0049.png",
	"res://art/rusher_360_px/rusher_360_a13_0049.png",
	"res://art/rusher_360_px/rusher_360_a14_0049.png",
	"res://art/rusher_360_px/rusher_360_a15_0049.png",
	"res://art/rusher_360_px/rusher_360_a16_0049.png",
	"res://art/rusher_360_px/rusher_360_a17_0049.png",
	"res://art/rusher_360_px/rusher_360_a18_0049.png",
	"res://art/rusher_360_px/rusher_360_a19_0049.png",
	"res://art/rusher_360_px/rusher_360_a20_0049.png",
	"res://art/rusher_360_px/rusher_360_a21_0049.png",
	"res://art/rusher_360_px/rusher_360_a22_0049.png",
	"res://art/rusher_360_px/rusher_360_a23_0049.png",
]
